"""ChatService orchestrating grounded RAG query generation."""

from typing import Any, List, Optional
from pydantic import BaseModel, ConfigDict, Field


from app.config import settings
from app.knowledge.exceptions import ChatServiceError
from app.knowledge.models.retrieval_result import RetrievalResult
from app.knowledge.rag.llm_service import LLMService
from app.knowledge.rag.prompt_builder import PromptBuilder
from app.knowledge.retrieval.retrieval_pipeline import RetrievalPipeline
from app.schemas.chat import SourceItem
from app.utils.logging import logger


class ChatServiceResult(BaseModel):
    """Domain model representing the output of ChatService execution."""

    model_config = ConfigDict(arbitrary_types_allowed=True)

    answer: str = Field(..., description="Grounded answer text generated by LLM")
    sources: List[SourceItem] = Field(default_factory=list, description="Extracted source document citations")
    confidence: Optional[float] = Field(default=None, description="Top chunk similarity confidence score")
    retrieval_result: Optional[Any] = Field(default=None, description="Underlying retrieval result object")



class ChatService:
    """Orchestrates end-to-end RAG workflow: RetrievalPipeline -> PromptBuilder -> LLMService.

    Strict Boundaries:
    - Never accesses Qdrant directly (delegates to RetrievalPipeline).
    - Never generates vector embeddings directly.
    - Never performs user authentication logic.
    """

    def __init__(
        self,
        retrieval_pipeline: Optional[RetrievalPipeline] = None,
        prompt_builder: Optional[PromptBuilder] = None,
        llm_service: Optional[LLMService] = None,
    ):
        """Initializes ChatService with injected dependency modules."""
        self.retrieval_pipeline = retrieval_pipeline or RetrievalPipeline()
        self.prompt_builder = prompt_builder or PromptBuilder()
        self.llm_service = llm_service or LLMService()

    def _extract_sources(self, retrieval_result: RetrievalResult) -> List[SourceItem]:
        """Extracts unique document and page citations from reranked retrieval results."""
        sources: List[SourceItem] = []
        seen = set()

        for chunk in retrieval_result.reranked_results:
            doc_name = chunk.document_name
            pages = chunk.page_numbers if chunk.page_numbers else [None]

            for pg in pages:
                key = (doc_name, pg)
                if key not in seen:
                    seen.add(key)
                    sources.append(SourceItem(document=doc_name, page=pg))

        return sources

    def ask(
        self,
        query: str,
        top_k: int = settings.RETRIEVAL_TOP_K,
        top_n: int = settings.RETRIEVAL_RERANK_TOP_N,
    ) -> ChatServiceResult:
        """Executes synchronous RAG question answering pipeline.

        Args:
            query (str): User question prompt.
            top_k (int): Number of initial vector matches to retrieve.
            top_n (int): Number of top reranked matches to select.

        Returns:
            ChatServiceResult: Generated answer, source citations, confidence, and metadata.

        Raises:
            ChatServiceError: If RAG processing fails.
        """
        if not query or not query.strip():
            raise ChatServiceError("User query cannot be empty.")

        logger.info(f"=== Starting ChatService.ask() for query: '{query[:60]}...' ===")

        try:
            # 1 & 2. Retrieve top K relevant chunks using existing RetrievalPipeline
            retrieval_result = self.retrieval_pipeline.retrieve(
                query=query,
                top_k=top_k,
                top_n=top_n,
            )

            # 3 & 4. Pass retrieved chunks into PromptBuilder to create production prompt
            prompt = self.prompt_builder.build_prompt(
                query=query,
                chunks=retrieval_result.reranked_results,
            )

            # 5. Call LLMService to generate answer
            answer = self.llm_service.generate(prompt)

            # 6. Extract source documents, page numbers, and confidence
            sources = self._extract_sources(retrieval_result)
            confidence = (
                round(retrieval_result.reranked_results[0].score, 4)
                if retrieval_result.reranked_results
                else None
            )

            logger.info("=== Completed ChatService.ask() successfully ===")

            return ChatServiceResult(
                answer=answer,
                sources=sources,
                confidence=confidence,
                retrieval_result=retrieval_result,
            )

        except Exception as e:
            logger.error(f"ChatService.ask() failed for query '{query}': {e}")
            raise ChatServiceError(f"ChatService execution error: {str(e)}") from e

    async def ask_async(
        self,
        query: str,
        top_k: int = settings.RETRIEVAL_TOP_K,
        top_n: int = settings.RETRIEVAL_RERANK_TOP_N,
    ) -> ChatServiceResult:
        """Executes asynchronous RAG question answering pipeline."""
        if not query or not query.strip():
            raise ChatServiceError("User query cannot be empty.")

        logger.info(f"=== Starting ChatService.ask_async() for query: '{query[:60]}...' ===")

        try:
            # 1 & 2. Retrieve top K relevant chunks using existing RetrievalPipeline
            retrieval_result = self.retrieval_pipeline.retrieve(
                query=query,
                top_k=top_k,
                top_n=top_n,
            )

            # 3 & 4. Pass retrieved chunks into PromptBuilder
            prompt = self.prompt_builder.build_prompt(
                query=query,
                chunks=retrieval_result.reranked_results,
            )

            # 5. Call LLMService asynchronously
            answer = await self.llm_service.generate_async(prompt)

            # 6. Extract sources & confidence
            sources = self._extract_sources(retrieval_result)
            confidence = (
                round(retrieval_result.reranked_results[0].score, 4)
                if retrieval_result.reranked_results
                else None
            )

            logger.info("=== Completed ChatService.ask_async() successfully ===")

            return ChatServiceResult(
                answer=answer,
                sources=sources,
                confidence=confidence,
                retrieval_result=retrieval_result,
            )

        except Exception as e:
            logger.error(f"ChatService.ask_async() failed for query '{query}': {e}")
            raise ChatServiceError(f"ChatService execution error: {str(e)}") from e
