"""ChatService orchestrating grounded RAG query generation with Answer Cache integration."""

import time
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, ConfigDict, Field

from app.config import settings
from app.knowledge.exceptions import ChatServiceError
from app.knowledge.models.retrieval_result import RetrievalResult
from app.knowledge.rag.answer_cache import answer_cache
from app.knowledge.rag.llm_service import LLMService
from app.knowledge.rag.prompt_builder import PromptBuilder
from app.knowledge.retrieval.retrieval_pipeline import RetrievalPipeline
from app.schemas.chat import SourceItem
from app.utils.logging import logger


class ChatServiceResult(BaseModel):
    """Domain model representing the output of ChatService execution."""

    model_config = ConfigDict(arbitrary_types_allowed=True)

    answer: str = Field(..., description="Grounded answer text generated by LLM")
    sources: List[SourceItem] = Field(default_factory=list, description="Extracted source document citations")
    confidence: Optional[float] = Field(default=None, description="Top chunk similarity confidence score")
    retrieval_result: Optional[Any] = Field(default=None, description="Underlying retrieval result object")
    timing: Dict[str, float] = Field(default_factory=dict, description="Stage latency timings in seconds")


class ChatService:
    """Orchestrates end-to-end RAG workflow: AnswerCache -> RetrievalPipeline -> PromptBuilder -> LLMService."""

    def __init__(
        self,
        retrieval_pipeline: Optional[RetrievalPipeline] = None,
        prompt_builder: Optional[PromptBuilder] = None,
        llm_service: Optional[LLMService] = None,
    ):
        """Initializes ChatService with injected dependency modules."""
        self.retrieval_pipeline = retrieval_pipeline or RetrievalPipeline()
        self.prompt_builder = prompt_builder or PromptBuilder()
        self.llm_service = llm_service or LLMService()

    def _extract_sources(self, retrieval_result: RetrievalResult, answer: str = "") -> List[SourceItem]:
        """Extracts unique document and page citations from company retrieval results ONLY."""
        if "available company documents do not contain sufficient evidence" in answer.lower():
            return []

        sources: List[SourceItem] = []
        seen = set()

        reranked = getattr(retrieval_result, "reranked_results", None) or []
        if isinstance(reranked, list):
            for chunk in reranked:
                doc_type = getattr(chunk, "document_type", "company")
                vis = getattr(chunk, "visibility", "user_visible")
                # HARD EVIDENCE BOUNDARY: Exclude internal instruction documents from citations
                if doc_type == "instruction" or vis == "internal":
                    continue

                doc_name = getattr(chunk, "document_name", "document.pdf")
                raw_pages = getattr(chunk, "page_numbers", None)
                pages = raw_pages if raw_pages else [None]

                for pg in pages:
                    key = (doc_name, pg)
                    if key not in seen:
                        seen.add(key)
                        sources.append(SourceItem(document=doc_name, page=pg))

        return sources

    def ask(
        self,
        query: str,
        top_k: int = settings.RETRIEVAL_TOP_K,
        top_n: int = settings.RETRIEVAL_RERANK_TOP_N,
        request_id: Optional[str] = None,
        tracker: Optional[Any] = None,
    ) -> ChatServiceResult:
        """Executes synchronous RAG question answering pipeline with Answer Cache."""
        if not query or not query.strip():
            raise ChatServiceError("User query cannot be empty.")

        t_service_start = time.perf_counter()

        # Check Answer Cache
        cached_payload = answer_cache.get(query)
        if cached_payload is not None:
            ans_text, cached_sources = cached_payload
            t_cache = time.perf_counter() - t_service_start
            logger.info(f"[ANSWER CACHE HIT] Returned answer in {t_cache:.4f}s for '{query[:40]}...'")
            return ChatServiceResult(
                answer=ans_text,
                sources=cached_sources,
                confidence=1.0,
                timing={
                    "cache_hit": 1.0,
                    "cache_lookup": round(t_cache, 4),
                    "chat_service_total": round(t_cache, 4),
                },
            )

        try:
            logger.info("[RAG STEP] RETRIEVAL START")
            retrieval_result = self.retrieval_pipeline.retrieve(
                query=query,
                top_k=top_k,
                top_n=top_n,
                request_id=request_id,
                tracker=tracker,
            )
            p_time = getattr(retrieval_result, "processing_time", 0.0)
            p_time_str = f"{p_time:.3f}s" if isinstance(p_time, (int, float)) else str(p_time)
            logger.info(f"[RAG STEP] RETRIEVAL END (Duration: {p_time_str})")

            logger.info("[RAG STEP] PROMPT BUILD START")
            t_pb_start = time.perf_counter()
            reranked = getattr(retrieval_result, "reranked_results", [])
            prompt = self.prompt_builder.build_prompt(
                query=query,
                chunks=reranked if isinstance(reranked, list) else [],
            )
            t_prompt_building = time.perf_counter() - t_pb_start
            logger.info(f"[RAG STEP] PROMPT BUILD END (Duration: {t_prompt_building:.3f}s)")

            logger.info("[RAG STEP] LLM REQUEST START")
            t_llm_start = time.perf_counter()
            answer = self.llm_service.generate(prompt, request_id=request_id, tracker=tracker)
            t_llm_generation = time.perf_counter() - t_llm_start
            logger.info(f"[RAG STEP] LLM RESPONSE RECEIVED (Duration: {t_llm_generation:.3f}s)")

            sources = self._extract_sources(retrieval_result, answer=answer)
            confidence = None
            if isinstance(reranked, list) and len(reranked) > 0 and hasattr(reranked[0], "score"):
                try:
                    confidence = round(float(reranked[0].score), 4)
                except Exception:
                    pass

            raw_timing = getattr(retrieval_result, "timing", {})
            ret_timing = raw_timing if isinstance(raw_timing, dict) else {}

            timing: Dict[str, float] = {
                **ret_timing,
                "prompt_building": round(t_prompt_building, 4),
                "llm_generation": round(t_llm_generation, 4),
                "chat_service_total": round(time.perf_counter() - t_service_start, 4),
            }

            # Put in answer cache
            answer_cache.put(query, answer, sources)

            return ChatServiceResult(
                answer=answer,
                sources=sources,
                confidence=confidence,
                retrieval_result=retrieval_result,
                timing=timing,
            )

        except Exception as e:
            logger.error(f"ChatService.ask() failed for query '{query}': {e}")
            raise ChatServiceError(f"ChatService execution error: {str(e)}") from e

    async def ask_async(
        self,
        query: str,
        top_k: int = settings.RETRIEVAL_TOP_K,
        top_n: int = settings.RETRIEVAL_RERANK_TOP_N,
        request_id: Optional[str] = None,
        tracker: Optional[Any] = None,
    ) -> ChatServiceResult:
        """Executes asynchronous RAG question answering pipeline with Answer Cache."""
        if not query or not query.strip():
            raise ChatServiceError("User query cannot be empty.")

        t_service_start = time.perf_counter()

        # Check Answer Cache
        cached_payload = answer_cache.get(query)
        if cached_payload is not None:
            ans_text, cached_sources = cached_payload
            t_cache = time.perf_counter() - t_service_start
            logger.info(f"[ANSWER CACHE HIT] Returned answer in {t_cache:.4f}s for '{query[:40]}...'")
            return ChatServiceResult(
                answer=ans_text,
                sources=cached_sources,
                confidence=1.0,
                timing={
                    "cache_hit": 1.0,
                    "cache_lookup": round(t_cache, 4),
                    "chat_service_total": round(t_cache, 4),
                },
            )

        try:
            logger.info("[RAG STEP] RETRIEVAL START")
            retrieval_result = self.retrieval_pipeline.retrieve(
                query=query,
                top_k=top_k,
                top_n=top_n,
                request_id=request_id,
                tracker=tracker,
            )
            p_time = getattr(retrieval_result, "processing_time", 0.0)
            p_time_str = f"{p_time:.3f}s" if isinstance(p_time, (int, float)) else str(p_time)
            logger.info(f"[RAG STEP] RETRIEVAL END (Duration: {p_time_str})")

            logger.info("[RAG STEP] PROMPT BUILD START")
            t_pb_start = time.perf_counter()
            reranked = getattr(retrieval_result, "reranked_results", [])
            prompt = self.prompt_builder.build_prompt(
                query=query,
                chunks=reranked if isinstance(reranked, list) else [],
            )
            t_prompt_building = time.perf_counter() - t_pb_start
            logger.info(f"[RAG STEP] PROMPT BUILD END (Duration: {t_prompt_building:.3f}s)")

            logger.info("[RAG STEP] LLM REQUEST START")
            t_llm_start = time.perf_counter()
            answer = await self.llm_service.generate_async(prompt, request_id=request_id, tracker=tracker)
            t_llm_generation = time.perf_counter() - t_llm_start
            logger.info(f"[RAG STEP] LLM RESPONSE RECEIVED (Duration: {t_llm_generation:.3f}s)")

            sources = self._extract_sources(retrieval_result, answer=answer)
            confidence = None
            if isinstance(reranked, list) and len(reranked) > 0 and hasattr(reranked[0], "score"):
                try:
                    confidence = round(float(reranked[0].score), 4)
                except Exception:
                    pass

            raw_timing = getattr(retrieval_result, "timing", {})
            ret_timing = raw_timing if isinstance(raw_timing, dict) else {}

            timing: Dict[str, float] = {
                **ret_timing,
                "prompt_building": round(t_prompt_building, 4),
                "llm_generation": round(t_llm_generation, 4),
                "chat_service_total": round(time.perf_counter() - t_service_start, 4),
            }

            # Put in answer cache
            answer_cache.put(query, answer, sources)

            return ChatServiceResult(
                answer=answer,
                sources=sources,
                confidence=confidence,
                retrieval_result=retrieval_result,
                timing=timing,
            )

        except Exception as e:
            logger.error(f"ChatService.ask_async() failed for query '{query}': {e}")
            raise ChatServiceError(f"ChatService execution error: {str(e)}") from e
