"""Manual test script running the requested profit question with API-level reasoning suppression."""

import asyncio
from pathlib import Path
import sys
import time

PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from app.config import settings
from app.knowledge.rag.chat_service import ChatService
from app.knowledge.rag.answer_cache import answer_cache
from app.knowledge.retrieval.query_embedding_cache import query_embedding_cache
from app.knowledge.retrieval.retrieval_pipeline import RetrievalPipeline


async def main():
    print("\n" + "=" * 90)
    print(" 🧪 MANUAL TEST: PROFIT QUESTION WITH API-LEVEL REASONING SUPPRESSION")
    print(f" Model: {settings.PRIMARY_MODEL}")
    print("=" * 90 + "\n")

    # Clear caches for fresh retrieval & LLM execution
    query_embedding_cache.clear()
    answer_cache.clear()

    pipeline = RetrievalPipeline()
    chat_service = ChatService(retrieval_pipeline=pipeline)

    query = "What is the profit generated by the company in their last financial year?"
    print(f"Query: '{query}'\n")

    t0 = time.perf_counter()
    res = await chat_service.ask_async(query)
    total_dur = time.perf_counter() - t0

    print("=" * 90)
    print(" FINAL ANSWER RECEIVED BY FRONTEND / CHATRESPONSE:")
    print("=" * 90)
    print(res.answer)
    print("=" * 90 + "\n")

    # Check for any leakage
    has_thinking = any(term in res.answer.lower() for term in ["thinking process", "analyze user question", "<think>"])
    print(f"Reasoning Leakage Present: {'YES (FAIL)' if has_thinking else 'NO (CLEAN PASS)'}")
    print(f"Total Execution Time: {total_dur:.3f}s\n")


if __name__ == "__main__":
    asyncio.run(main())
