"""Script verifying generation quality, reasoning isolation, finish_reason diagnosis, and answer completeness on target questions."""

import asyncio
from pathlib import Path
import sys
import time

PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from app.config import settings
from app.knowledge.rag.chat_service import ChatService
from app.knowledge.rag.answer_cache import answer_cache
from app.knowledge.retrieval.query_embedding_cache import query_embedding_cache
from app.knowledge.retrieval.retrieval_pipeline import RetrievalPipeline


async def run_verification():
    print("\n" + "=" * 90)
    print(" 🧪 TECHONOMY LLM RESPONSE QUALITY & COMPLETION VERIFICATION")
    print(f" Model: {settings.PRIMARY_MODEL}")
    print("=" * 90 + "\n")

    # Clear caches to ensure fresh LLM calls
    query_embedding_cache.clear()
    answer_cache.clear()

    pipeline = RetrievalPipeline()
    chat_service = ChatService(retrieval_pipeline=pipeline)

    test_questions = [
        ("A", "What was the company's revenue in 2025?"),
        ("B", "What was the profit generated by the company in their last financial year?"),
        ("C", "Who are the current owners of the company? Tell me more about the ownership details and marketing strategies of the company."),
    ]

    for label, query in test_questions:
        print(f"------------------------------------------------------------------------------------------")
        print(f" QUESTION {label}: '{query}'")
        print(f"------------------------------------------------------------------------------------------")

        t0 = time.perf_counter()
        res = await chat_service.ask_async(query)
        total_dur = time.perf_counter() - t0

        ret_time = res.timing.get("retrieval_total", 0.0)
        llm_time = res.timing.get("llm_generation", 0.0)

        # Check if reasoning/thinking text exists in answer
        reasoning_detected = any(term in res.answer.lower() for term in ["<think>", "</think>", "thinking process", "let me analyze"])

        print(f"Model Used: {settings.PRIMARY_MODEL}")
        print(f"Generation Latency: {llm_time:.3f}s | Total Request Latency: {total_dur:.3f}s")
        print(f"Reasoning Hidden: {'YES (Clean)' if not reasoning_detected else 'NO (Leaked)'}")
        print(f"Sources Cited: {len(res.sources)}")
        print("\nGenerated Answer:")
        print(res.answer)
        print("\n" + "=" * 90 + "\n")


if __name__ == "__main__":
    asyncio.run(run_verification())
