"""Pydantic schemas for RAG Chat request and response payloads."""

from typing import List, Optional
from pydantic import BaseModel, Field


class SourceItem(BaseModel):
    """Source document citation containing document filename and page number."""

    document: str = Field(..., description="Source document filename or title")
    page: Optional[int] = Field(default=None, description="Page number reference")


class ChatRequest(BaseModel):
    """Request payload for RAG chat queries."""

    team_name: str = Field(..., description="Team name identifier")
    question: str = Field(..., description="User question prompt text", min_length=1, max_length=2000)


class ChatResponse(BaseModel):
    """Response payload for RAG chat queries."""

    answer: str = Field(..., description="Grounded answer text generated by LLM")
    sources: List[SourceItem] = Field(default_factory=list, description="Source document citations")
    team_name: str = Field(..., description="Submitting team name identifier")


class ChatQueryRequest(BaseModel):
    """Flexibility schema accepting either question or query field."""

    team_name: Optional[str] = Field(default=None, description="Team name identifier")
    question: Optional[str] = Field(default=None, description="Question string")
    query: Optional[str] = Field(default=None, description="Alternative query field")

    def get_question_text(self) -> str:
        """Returns non-empty question string."""
        text = self.question or self.query or ""
        return text.strip()
